# Generated by Django 5.1.1 on 2024-10-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posts_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='fecha',
            new_name='fecha_publicacion',
        ),
        migrations.AlterField(
            model_name='posts',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/posts'),
        ),
    ]
