# Generated by Django 4.2.16 on 2024-10-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_posts_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="slug",
            field=models.SlugField(blank=True, editable=False, max_length=200),
        ),
    ]
