# Generated by Django 4.2.16 on 2024-10-13 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_posts_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentarios",
            name="autor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comentarios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comentarios",
            name="contenido",
            field=models.TextField(max_length=150, verbose_name="Contenido"),
        ),
        migrations.AlterField(
            model_name="comentarios",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="comentarios",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comentarios",
                to="posts.posts",
            ),
        ),
    ]
