# Generated by Django 5.1.1 on 2024-09-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorias',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='content',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='publication_date',
            new_name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='title',
        ),
        migrations.AddField(
            model_name='posts',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/posts'),
        ),
        migrations.AddField(
            model_name='posts',
            name='titulo',
            field=models.CharField(default=1, max_length=250, verbose_name='Titulo'),
            preserve_default=False,
        ),
    ]
